POST http://localhost:3001/api/ideas/
Content-Type: application/json

{
    "title": "AAAA", 
    "problemStatement": {
        "domain": "tbd",
        "stateOfTheArt": "tbd",
        "solution": "tbd"
    },
    "author": "Joie de",
    "upVote": 12,
    "downVote": 16,
    "questions": [],
    "criticisms": [],
    "user": "6080b8434f78de27e82a6d04"
}