POST http://localhost:3001/api/ideas/
Content-Type: application/json

{
    "title": "TBD", 
    "problemStatement": {
        "domain": "tbd",
        "stateOfTheArt": "tbd",
        "solution": "tbd"
    },
    "author": "Joie de",
    "upVote": 12,
    "downVote": 16,
    "questions": [],
    "criticisms": [],
    "user": "60738ff358e6195894b41607"
}